const authConstants = {
  IS_CACCOUNT__SIGNIN_FAIL: "IS_CACCOUNT__SIGNIN_FAIL",

  SIGNIN_REQUEST: "SIGNIN_REQUEST",
  FIRST_TIMER: "FIRST_TIMER",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAIL: "SIGNIN_FAIL",
  IS_SIGNIN_FAIL: "IS_SIGNIN_FAIL",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAIL: "SIGNUP_FAIL",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAIL: "FORGOT_PASSWORD_FAIL",

  SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNOUT_FAIL: "SIGNOUT_FAIL",

  CHECK_OTP_REQUEST: "CHECK_OTP_REQUEST",
  CHECK_OTP_SUCCESS: "CHECK_OTP_SUCCESS",
  CHECK_OTP_FAIL: "CHECK_OTP_FAIL",
};

const cartConstant = {
  GET_CART_COUNT_REQUEST: "GET_CART_COUNT_REQUEST",
  GET_CART_COUNT_SUCCESS: "GET_CART_COUNT_SUCCESS",
  GET_CART_COUNT_FAIL: "GET_CART_COUNT_FAIL",

  CART_AND_CRUD_REQUEST: "CART_AND_CRUD_REQUEST",
  CART_AND_CRUD_SUCCESS: "CART_AND_CRUD_SUCCESS",
  CART_AND_CRUD_FAIL: "CART_AND_CRUD_FAIL",

  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAIL: "GET_CART_FAIL",

  GET_CART_ITEMS_REQUEST: "GET_CART_ITEMS_REQUEST",
  GET_CART_ITEMS_SUCCESS: "GET_CART_ITEMS_SUCCESS",
  GET_CART_ITEMS_FAIL: "GET_CART_ITEMS_FAIL",
};

const orderConstant = {
  ORDER_CRUD_REQUEST: "ORDER_CRUD_REQUEST",
  ORDER_CRUD_SUCCESS: "ORDER_CRUD_SUCCESS",
  ORDER_CRUD_FAIL: "ORDER_CRUD_FAIL",

  GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
  GET_ORDER_FAIL: "GET_ORDER_FAIL",

  GET_ORDER_ITEMS_REQUEST: "GET_ORDER_ITEMS_REQUEST",
  GET_ORDER_ITEMS_SUCCESS: "GET_ORDER_ITEMS_SUCCESS",
  GET_ORDER_ITEMS_FAIL: "GET_ORDER_ITEMS_FAIL"
};

const appConstant = {
  GET_APP_REQUEST: "GET_APP_REQUEST",
  GET_APP_SUCCESS: "GET_APP_SUCCESS",
  GET_APP_FAIL: "GET_APP_FAIL",

  UPDATE_APP_REQUEST: "UPDATE_APP_REQUEST",
  UPDATE_APP_SUCCESS: "UPDATE_APP_SUCCESS",
  UPDATE_APP_FAIL: "UPDATE_APP_FAIL",
};
const productConstant = {
  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL: "GET_PRODUCTS_FAIL",

  GET_SEARCH_REQUEST: "GET_SEARCH_REQUEST",
  GET_SEARCH_SUCCESS: "GET_SEARCH_SUCCESS",
  GET_SEARCH_FAIL: "GET_SEARCH_FAIL",

  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAIL: "GET_PRODUCT_FAIL",

  CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL: "CREATE_PRODUCT_FAIL",


  GET_COMMENTS_REQUEST: "  GET_COMMENTS_REQUEST",
  GET_COMMENTS_SUCCESS: "  GET_COMMENTS_SUCCESS",
  GET_COMMENTS_FAIL: "  GET_COMMENTS_FAIL",

ADD_LIKE_REQUEST:"ADD_LIKE_REQUEST",
ADD_LIKE_SUCCESS:"ADD_LIKE_SUCCESS",
ADD_LIKE_FAIL:"ADD_LIKE_FAIL",

  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAIL: "ADD_COMMENT_FAIL",

  GET_LIKES_REQUEST: "GET_LIKES_REQUEST",
  GET_LIKES_SUCCESS: "GET_LIKES_SUCCESS",
  GET_LIKES_FAIL: "GET_LIKES_FAIL",


DELETE_COMMENT_REQUEST:"DELETE_COMMENT_REQUEST",
DELETE_COMMENT_SUCCESS:"DELETE_COMMENT_SUCCESS",
DELETE_COMMENT_FAIL:"DELETE_COMMENT_FAIL",

UPDTATE_COMMENT_REQUEST:"UPDTATE_COMMENT_REQUEST",
UPDTATE_COMMENT_SUCCESS:"UPDTATE_COMMENT_SUCCESS",
UPDTATE_COMMENT_FAIL:"UPDTATE_COMMENT_FAIL",

GET_POSTS_REQUEST:"GET_POSTS_REQUEST",
GET_POSTS_SUCCESS:"GET_POSTS_SUCCESS",
GET_POSTS_FAIL:"GET_POSTS_FAIL",

GET_POST_REQUEST:"GET_POST_REQUEST",
GET_POST_SUCCESS:"GET_POST_SUCCESS",
GET_POST_FAIL:"GET_POST_FAIL",

POST_CRUD_REQUEST:"POST_CRUD_REQUEST",
POST_CRUD_SUCCESS:"POST_CRUD_SUCCESS",
POST_CRUD_FAIL:"POST_CRUD_FAIL",

GET_SAVED_REQUEST:"GET_SAVED_REQUEST",
GET_SAVED_SUCCESS:"GET_SAVED_SUCCESS",
GET_SAVED_FAIL:"GET_SAVED_FAIL",


};

const postContstant = {
  
}

const paymentConstants = {
  INITIATE_NEW_PAYMENT_REQUEST: "INITIATE_NEW_PAYMENT_REQUEST",
  INITIATE_NEW_PAYMENT_SUCCESS: "INITIATE_NEW_PAYMENT_SUCCESS",
  INITIATE_NEW_PAYMENT_FAIL: "INITIATE_NEW_PAYMENT_FAIL",
};

const contactConstant = {
  GET_CONTACTS_REQUEST: "GET_CONTACTS_REQUEST",
  GET_CONTACTS_SUCCESS: "GET_CONTACTS_SUCCESS",
  GET_CONTACTS_FAIL: "GET_CONTACTS_FAIL",

  GET_CONTACT_REQUEST: "GET_CONTACT_REQUEST",
  GET_CONTACT_SUCCESS: "GET_CONTACT_SUCCESS",
  GET_CONTACT_FAIL: "GET_CONTACT_FAIL",

  CREATE_CONTACT_REQUEST: "CREATE_CONTACT_REQUEST",
  CREATE_CONTACT_SUCCESS: "CREATE_CONTACT_SUCCESS",
  CREATE_CONTACT_FAIL: "CREATE_CONTACT_FAIL",
};
const registerConstant = {
  ONBOARDING_REQUEST: "ONBOARDING_REQUEST",
  ONBOARDING_SUCCESS: "ONBOARDING_SUCCESS",
  ONBOARDING_FAIL: "ONBOARDING_FAIL",

  ADD_SUPER_ADMIN_REQUEST: "ADD_SUPER_ADMIN_REQUEST",
  ADD_SUPER_ADMIN_SUCCESS: "ADD_SUPER_ADMIN_SUCCESS",
  ADD_SUPER_ADMIN_FAIL: "ADD_SUPER_ADMIN_FAIL",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAIL: "SIGNUP_FAIL",

  GET_CACCOUNT_ACCOUNT_ACTIVATION_BY_SLUG_REQUEST:
    "GET_CACCOUNT_ACCOUNT_ACTIVATION_BY_SLUG_REQUEST",
  GET_CACCOUNT_ACCOUNT_ACTIVATION_BY_SLUG_SUCCESS:
    "GET_CACCOUNT_ACCOUNT_ACTIVATION_BY_SLUG_SUCCESS",
  GET_CACCOUNT_ACCOUNT_ACTIVATION_BY_SLUG_FAIL:
    "GET_CACCOUNT_ACCOUNT_ACTIVATION_BY_SLUG_FAIL",

  ACTIVATE_REQUEST: "ACTIVATE_REQUEST",
  ACTIVATE_SUCCESS: "ACTIVATE_SUCCESS",
  ACTIVATE_FAIL: "ACTIVATE_FAIL",
};
const membersConstant = {
  CREATE_ACCOUNT_REQUEST: "CREATE_ACCOUNT_REQUEST",
  CREATE_ACCOUNT_SUCCESS: "CREATE_ACCOUNT_SUCCESS",
  CREATE_ACCOUNT_FAIL: "CREATE_ACCOUNT_FAIL",

  GET_ALL_MEMBERS_REQUEST: "GET_ALL_MEMBERS_REQUEST",
  GET_ALL_MEMBERS_SUCCESS: "GET_ALL_MEMBERS_SUCCESS",
  GET_ALL_MEMBERS_FAIL: "GET_ALL_MEMBERS_FAIL",

  GET_MY_PROFILE_REQUEST: "GET_MY_PROFILE_REQUEST",
  GET_MY_PROFILE_SUCCESS: "GET_MY_PROFILE_SUCCESS",
  GET_MY_PROFILE_FAIL: "GET_MY_PROFILE_FAIL",

  PROFILE_UPDATE_REQUEST: "PROFILE_UPDATE_REQUEST",
  PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
  PROFILE_UPDATE_FAIL: "PROFILE_UPDATE_FAIL",

  DELETE_MEMBER_REQUEST: "DELETE_MEMBER_REQUEST",
  DELETE_MEMBER_SUCCESS: "DELETE_MEMBER_SUCCESS",
  DELETE_MEMBER_FAIL: "DELETE_MEMBER_FAIL",

  PROFILE_SETTINGS_REQUEST: "PROFILE_SETTINGS_REQUEST",
  PROFILE_SETTINGS_SUCCESS: "PROFILE_SETTINGS_SUCCESS",
  PROFILE_SETTINGS_FAIL: "PROFILE_SETTINGS_FAIL",

  ADD_NEW_MEMBER_REQUEST: "ADD_NEW_MEMBER_REQUEST",
  ADD_NEW_MEMBER_SUCCESS: "ADD_NEW_MEMBER_SUCCESS",
  ADD_NEW_MEMBER_FAIL: "ADD_NEW_MEMBER_FAIL",

  ADD_USERS_REQUEST: "ADD_USERS_REQUEST",
  ADD_USERS_SUCCESS: "ADD_USERS_SUCCESS",
  ADD_USERS_FAIL: "ADD_USERS_FAIL",

  GET_MEDIA_REQUEST: "GET_MEDIA_REQUEST",
  GET_MEDIA_SUCCESS: "GET_MEDIA_SUCCESS",
  GET_MEDIA_FAIL: "GET_MEDIA_FAIL",

  MEDIA_CRUD_REQUEST: "MEDIA_CRUD_REQUEST",
  MEDIA_CRUD_SUCCESS: "MEDIA_CRUD_SUCCESS",
  MEDIA_CRUD_FAIL: "MEDIA_CRUD_FAIL",

  GET_ALL_AUTH_ACCOUNTS_REQUEST: "GET_ALL_AUTH_ACCOUNTS_REQUEST",
  GET_ALL_AUTH_ACCOUNTS_SUCCESS: "GET_ALL_AUTH_ACCOUNTS_SUCCESS",
  GET_ALL_AUTH_ACCOUNTS_FAIL: "GET_ALL_AUTH_ACCOUNTS_FAIL",

  USER_PROFILE_REQUEST: "USER_PROFILE_REQUEST",
  USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  USER_PROFILE_FAIL: "USER_PROFILE_FAIL",

  PERSONAL_PROFILE_REQUEST: "PERSONAL_PROFILE_REQUEST",
  PERSONAL_PROFILE_SUCCESS: "PERSONAL_PROFILE_SUCCESS",
  PERSONAL_PROFILE_FAIL: "PERSONAL_PROFILE_FAIL",

  DASHBOARD_REQUEST: "DASHBOARD_REQUEST",
  DASHBOARD_SUCCESS: "DASHBOARD_SUCCESS",
  DASHBOARD_FAIL: "DASHBOARD_FAIL",
};

const serverConstants = {
  SERVER_ERROR: "SERVER_ERROR",
  SERVER_NETWORK: "SERVER_NETWORK",
  SYSTEM_TIMEOUT: "SYSTEM_TIMEOUT",
};
export {
  authConstants,
  registerConstant,
  membersConstant,
  serverConstants,
  cartConstant,
  productConstant,
  contactConstant,
  orderConstant,
  paymentConstants,
  appConstant,
};
