const initState = {
  signIn: {
    user: {},
    authenticate: false,
    authenticating: false,
    info: "",
    error: null,
    message: "",
    token: "",
    loading: false,
  },
  signUp: {
    error: null,
    info: "",
    data: {},
    loading: false,
    completed: false,
  },

  userProfile: {
    loadingOrders: false,
    loadingPendings: false,
    loadingAdmins: false,
    loadingCustomers: false,
    loadingProducts: false,
    loadingCompletedOrders: false,
    loadingLikedProducts: false,
    loadingSharedProducts: false,
    loadingSavedProducts: false,
    wishlists: [],
loadingWishlists: false,
    loadingEarnings: false,
    loadingCarts: false,
    orders: [],
    pendings: [],
    admins: [],
    customers: [],
    products: [],
    completedOrders: [],
    likedProducts: [],
    sharedProducts: [],
    savedProducts: [],
    carts: [],
    earnings: [],

    error: "",
    status: null,
  },

  users: {
    members: [],
    updateLoading: false,
    loading: false,
    error: "",
    status: null,
    updateCompleted: false,
  },
  dialogModal: {
    open: false,
  },
  cart: {
    loadingCart: false,
    cartItem: null,
    loading: false,
    newCart: null,
    cartCount: 0,
    loadingNewCart: false,
    carts: [],
    info: "",
    error: null,
  },

  order: {
    orders: [],
    order: null,
    loadingOrder: false,
    status: null,
    info: "",
    error: null,
    loading: false,
  },
  newTransaction: {
    data: null,
    loading: false,
    info: "",
    status: null,
    error: null,
  },
  products: {
    automobiles: [],
    hotels: [],
    all: [],
    properties: [],
    shortlets: [],
    init: null,
    products: [],
    interiors: [],
    draft: [],
    product: null,
    newProduct: null,
    completed: false,
    loadingNewProduct: false,
    updated: null,
    loading: false,
    loadingProduct: false,
    info: "",
    error: null,
    status: null,
  },
  posts: {
    automobiles: [],
    hotels: [],
    all: [],
    properties: [],
    shortlets: [],
    init: null,
    products: [],
    interiors: [],
    draft: [],
    product: null,
    newProduct: null,
    completed: false,
    loadingNewProduct: false,
    updated: null,
    loading: false,
    loadingProduct: false,
    info: "",
    error: null,
    status: null,
  },

  likes:{
    loadinglikes: false,
data: [],
error: null,
info: ''
  },

  comments: {
    comments: [],
    loadingComments: false,
    newComment: null,
    loadingComment: false,
    info: null,
    error: null,
  },

  serverData: {
    data: [],
    error: null,
    satus: null,
    loading: false,
    info: "",
  },

  app: {
    data: null,
    analytics: [],
    error: null,
    satus: null,
    loading: false,
    info: "",
    target: null,
    loadingUpdate: false,
  },
  createAccount: {
    data: {},
    error: null,
    completed: false,
    info: "",
    loading: false,
  },

  media: {
    data: [],
    info: "",
    error: null,
    loading: false,
    loadingNew: false,
    newImage: {},
    statue: null,
  },
  contactUs: {
    data: [],
    info: "",
    error: null,
    loading: false,
    loadingNew: false,
    newContactUs: {},
    statue: null,
  },

  otp: {
    data: {},
    error: null,
    info: "",
    loading: false,
  },
};

export default initState;
